### ISSUE TITLE
constraints

### ISSUE THREAD

**Issue by SneakyFernando** [tomilov/sweepline#3]
Hello. Great project. 
1. The result is weird when I use float as value type. Does it support float?
2.  Does it handle case when some points has same position?
3. Sometimes it returns <3 edges, why does that happen? I am feeding 4 extra corner sites to ensure impermeability, but looks like its not enough to ensure >=3 edges in any scenario. 
Edit: the problem was in the sites overlapping, indeed it doesnt handle this case which caused a mess.

**Comment by tomilov** [comment]
It is expected, that there are no equivalent sites in input.
